# Generated by Django 5.0.2 on 2025-03-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="candidate",
        ),
        migrations.AddField(
            model_name="task",
            name="candidates",
            field=models.ManyToManyField(
                related_name="tasks", to="candidates.candidate"
            ),
        ),
    ]
